version: '3'

services:

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "spider"
    #volumes:
    #  - datvolume:/var/lib/mysql

    restart: always
    ports:
      - "3306:3306"
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped 
    ports:
      - "8080:8080"
volumes:
  datvolume:
