version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "spider"
      MYSQL_DATABASE: "spider"
      MYSQL_USER: "spider"
      MYSQL_PASSWORD: "spider"
    volumes:
     - ./data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    command: node /usr/src/app/crawler.js
    container_name: nodejs
    ports:
      - "8080:8080"
    depends_on: 
      - mysql
      
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  datvolume:
