version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "spider"
      MYSQL_DATABASE: "spider"
      MYSQL_USER: "spider"
      MYSQL_PASSWORD: "spider"
    volumes:
     - ./data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    command: node /usr/src/app/dashboard/api.js
    container_name: api
    ports:
      - "8080:3000"
    restart: unless-stopped
    depends_on: 
      - mysql

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    command: node /usr/src/app/crawler.js
    container_name: nodejs
    restart: unless-stopped
    volumes:
      - ${PWD}/counter.txt:/usr/src/app/counter.txt
    depends_on: 
      - mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  datvolume: